Master
jahirfiquitiva/Kuper pull request #98
Opened 2024-12-28 20:57 UTC by bhaskar966

### Description

I added support for Android 15 and found a small bug in a function named "clearBitmap" so I fixed that.
To make the app useable and buildable I needed to update the AGP version as well as opt-out from edge to edge view.
Regarding edge-to-edge, I  prefer that you or someone who knows about XML layouts adapt the design according to the guidelines of Andordi 15.

### Motivation

I wanted my own apps to support Android 15, so updated here too.

2024-12-30 14:41 UTC, jahirfiquitiva requested changes

2024-12-30 14:41 UTC, jahirfiquitiva commented on library/src/main/kotlin/dev/jahir/kuper/data/models/Component.kt
> +                Log.e("clearBitmap", "newBitmap is null")
please remove this log

2024-12-30 14:41 UTC, jahirfiquitiva commented on app/src/main/kotlin/dev/jahir/kuper/app/MainActivity.kt
> -
please revert this change

2024-12-30 18:38 UTC, bhaskar966 commented on library/src/main/kotlin/dev/jahir/kuper/data/models/Component.kt
> +                Log.e("clearBitmap", "newBitmap is null")
Removed the log.

2024-12-30 18:39 UTC, bhaskar966 commented on app/src/main/kotlin/dev/jahir/kuper/app/MainActivity.kt
> -
Now, there are no changes in MainActivity. Sorry for the mistake 😅

2025-01-02 14:46 UTC, jahirfiquitiva approved these changes

2025-01-02 14:47 UTC, jahirfiquitiva commented
thanks for the help @bhaskar966

2025-01-02 14:47 UTC, merged